//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasketballMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Basketball
    {
        public int BallId { get; set; }

        [StringLength(100)]
        [Required(ErrorMessage = "Please Enter Player Name")]
        public string PlayerName { get; set; }

        [Required(ErrorMessage = "Please Enter your Exercise")]
        public string Exercise { get; set; }

        [Range(1, 120)]
        [Required(ErrorMessage = "Please Enter Duration of Exercise")]
        public int ExerciseDuration { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Please enter date in format of DD/MM/YYYY")]
        public DateTime ExerciseDate { get; set; }

    }
}
